version: '3'
services:
  cozy-app-dev:
    image: "cozy/cozy-app-dev:1.3.1"
    ports:
    - "8025:8025"
    - "8080:8080"
    volumes:
    - "./public:/data/cozy-app"
    - "./tmp/couchdb:/usr/local/couchdb/data"
    - "./tmp/cozy-storage:/data/cozy-storage"
